name: CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2.0.0

    - name: Use node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
        registry-url: https://registry.npmjs.org

    # - name: adonis cli
    #   run: npm install -g @adonisjs/cli
    - name: install
      run: npm install
    # - name: generate key
    #   run: adonis key:generate
    - name: lint
      run: npm run lint
    - name: test frontend
      run: npm run test-frontend
    # - name: test backend // github doesn't support server side functions
    #   run: npm run test
    - name: build
      run: npm run prod
